name: solid_logger
description: >
  A professional and lightweight logging library for Flutter and Dart,
  providing structured and configurable log output for apps and packages.

version: 0.1.1

environment:
  sdk: '>=3.0.0 <4.0.0'

# Homepage / repository
homepage: https://github.com/devnizamuddin/solid_logger
repository: https://github.com/devnizamuddin/solid_logger

# License (MIT is common)
license: MIT

# Optional keywords for pub.dev
keywords:
  - logging
  - logger
  - debug
  - flutter
  - dart
  - pretty-log
  - solid-logger

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
  test: ^1.26.0

flutter:
  uses-material-design: false
